### ISSUE TITLE
Create issues for closed tasks on the main Godot Engine repository.

### ISSUE THREAD

**Issue by fire** [godotengine/godot-visual-script#2]
Create issues for closed tasks on the main Godot Engine repository to re-evalulate them. Only create them if someone is planning to work on them in the near 3 month future.

- [ ] Add subgraphing in VisualScript to create modular nodes #59434
- [ ] Fixed functions in visual script not showing correct return value type #58581
- [ ] Fix cannot get VisualScriptPropertySet in visual property selector #58179
- [ ] Remove VisualScriptVariableGet VisualScriptVariableSet #55152
- [ ] Remove VisualScriptSubCall #55150
- [ ] [4.0] Fix output port type mismatch for some VisualScript nodes #51147
- [ ] Make sequence ports selectable on all VisualScriptNodes (FAILD) #55149
- [ ] Add type validations when setting basic type #53465
- [ ] Visual script modules draft #51050
- [ ] VisualScript callable nodes not getting updated- Fix #38148
- [ ] Enhance visual script, selection area popped up when disconnected nodes #40045
- [ ] VisualScript Modules #45294 
- [ ] Remi left some references to VisualScript in the code outside modules/visual_script/ which are needed for users who would compile the C++ module in a custom build. If VisualScript is ported to an extension and further maintained, one aim should be to remove the need for those hardcoded references so that the extension is fully modular.

See also https://github.com/orgs/godotengine/projects/29.

**Comment by fire** [comment]
Discussion with @YuriSizov was that we can transfer the open issues from godot engine's other repos here.

**Comment by fire** [comment]
The issues have been transferred.
